-- 코드를 입력하세요
SELECT A.CAR_ID, 
    A.CAR_TYPE,
    ROUND(DAILY_FEE *(1-C.DISCOUNT_RATE/100)*30) FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID=B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE=C.CAR_TYPE
WHERE (A.CAR_TYPE='세단'
OR A.CAR_TYPE='SUV')
AND C.DURATION_TYPE='30일 이상' 
GROUP BY A.CAR_ID
HAVING (MAX(END_DATE)<'2022-11-01'
OR MIN(START_DATE)>'2022-11-30')
AND FEE>=500000 AND FEE<2000000
ORDER BY 3 DESC,2, 1 DESC;