-- 코드를 입력하세요
SELECT A.FOOD_TYPE, A.REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A
WHERE (FOOD_TYPE,FAVORITES) 
IN (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
FROM REST_INFO
GROUP BY 1) 
# ON A.REST_ID=B.REST_ID
# on a.favorites=b.favorites
ORDER BY 1 DESC