-- 코드를 작성해주세요
select ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1) ,'km') TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
FROM subway_distance
group by route
ORDER BY SUM(D_BETWEEN_DIST) DESC